name: frontend
description: "Dissertation 2024-2025"
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: packages/cache
  cupertino_icons: ^1.0.6
  bloc: ^9.0.0
  camera: ^0.11.0+2
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  go_router: ^14.6.2
  firebase_auth: ^5.3.4
  logger: ^2.5.0
  alert_banner: ^1.0.1
  dio: ^5.7.0
  get_it: ^8.0.3
  carousel_slider: ^5.0.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.2
  model_viewer_plus: ^1.9.1
  flutter_3d_controller: ^2.1.0
  hydrated_bloc: ^10.0.0
  dart_mappable: ^4.4.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  flutter_gen: ^5.10.0
  google_fonts: ^6.2.1
  fl_chart: ^0.71.0
  remixicon: ^1.4.1
  fluttertoast: ^8.2.12
  firebase_crashlytics: ^4.3.5
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.4.0
  build_runner: ^2.4.15
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  vector_graphics_compiler: ^1.1.16
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

  assets:
    - assets/test_object.glb
    - assets/svg/camera-1-48.svg.vec
    - assets/images/27-0.png 
    - assets/images/27-1.png 
    - assets/images/27-2.png 
    - assets/images/27-3.png 
    - assets/images/27-4.png 
    - assets/images/27-5.png 
    - assets/images/27-6.png 
    - assets/images/27-7.png 
    - assets/images/27-8.png 
    - assets/images/27-9.png 
    - assets/images/27-10.png 
    - assets/images/27-11.png 
    - assets/images/27-12.png 
    - assets/images/27-13.png 
    - assets/images/27-14.png 
    - assets/images/27-15.png 
    - assets/images/27-16.png 
    - assets/images/27-17.png 
    - assets/images/27-18.png 
    - assets/images/27-19.png 
    - assets/images/27-20.png 
    - assets/images/27-21.png 
    - assets/images/27-22.png 
    - assets/images/27-23.png 
    - assets/images/27-24.png 
    - assets/images/27-25.png 
    - assets/images/27-26.png 
    - assets/images/27-27.png 
    - assets/images/27-28.png 
    - assets/images/27-29.png 
    - assets/images/27-30.png 
    - assets/images/27-31.png 
    - assets/images/27-32.png 
    - assets/images/27-33.png 
    - assets/images/27-34.png 
    - assets/images/27-35.png 
    - assets/images/27-36.png 
    - assets/images/27-37.png 
    - assets/images/27-38.png 
    - assets/images/27-39.png 
    - assets/images/27-40.png 
    - assets/images/27-41.png 
    - assets/images/27-42.png 
    - assets/images/27-43.png 
    - assets/images/27-44.png 
    - assets/images/27-45.png 
    - assets/images/27-46.png 
    - assets/images/27-47.png 
    - assets/images/27-48.png 
    - assets/images/27-49.png 
    - assets/images/27-50.png 
    - assets/images/27-51.png 
    - assets/images/27-52.png 
    - assets/images/27-53.png 
    - assets/images/27-54.png 
    - assets/images/27-55.png 
    - assets/images/27-56.png 
    - assets/images/27-57.png 
    - assets/images/27-58.png 
    - assets/images/27-59.png 
    - assets/images/27-60.png 
    - assets/images/27-61.png 
    - assets/images/27-62.png 
    - assets/images/27-63.png 
    - assets/images/27-64.png 
    - assets/images/27-65.png 
    - assets/images/27-66.png 
    - assets/images/27-67.png 
    - assets/images/27-68.png 
    - assets/images/27-69.png 
    - assets/images/27-70.png 
    - assets/images/27-71.png 
    - assets/images/27-72.png 
    - assets/images/27-73.png 
    - assets/images/27-74.png 
    - assets/images/27-75.png 
    - assets/images/27-76.png 
    - assets/images/27-77.png 
    - assets/images/27-78.png 
    - assets/images/27-79.png 
    - assets/images/27-80.png 
    - assets/images/27-81.png 
    - assets/images/27-82.png 
    - assets/images/27-83.png